version: '3'
services:
    frontend:
        container_name: frontend
        build: ./FrontEnd
        ports:
            - "3000:3000"
    backend:
        container_name: backend
        build: ./BackEnd
        ports:
            - "4444:4444"
    nginx:
        container_name: nginx
        build: ./docker/nginx
        ports:
            - 80:80
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        depends_on:
            - mysqldb
    mysqldb:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - "./docker/database/db/mysql:/var/lib/mysql"
    #certbot:
    #   image: certbot/certbot:latest
    #   command: certonly --renew-by-default --standalone --email thallot42@gmail.com --agree-tos --no-eff-email -d footedia.com -d www.footedia.com
    #   volumes:
    #       - ./certbot/conf:/etc/letsencrypt
    #       - ./certbot/logs:/var/log/letsencrypt
    #       - ./certbot/data:/var/www/certbot
